### ISSUE TITLE
Incorrect log for maven pom file found

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/sti-wildfly#53]
In https://github.com/openshift/sti-wildfly/blob/master/8.1/.sti/bin/assemble#L183
````
"Found pom.xml... attempting to build with 'mvn -e ${MAVEN_ARGS}'"
````

But then when executed maven "-e option" is not passed:

https://github.com/openshift/sti-wildfly/blob/master/8.1/.sti/bin/assemble#L186
````
mvn $MAVEN_ARGS
````

**Comment by bparees** [comment]
thanks for fixing this.
