### ISSUE TITLE
Is maven 3.0.5 used by any special reason? Can be bumped up to latest?

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/sti-wildfly#55]
There is a new version of maven that supports defining proxy via command line. It should be easier than shipping a custom settings.xml and provide ENV.

**Comment by bparees** [comment]
no particular reason, if you want to do a PR i'll be happy to merge it.

**Comment by bparees** [comment]
fixed by https://github.com/openshift/sti-wildfly/pull/56
