### ISSUE TITLE
update to Wildfly 10.0.0.Final

### ISSUE THREAD

**Issue by quentinburley** [openshift/sti-wildfly#67]
update to Wildfly 10.0.0.Final

**Comment by quentinburley** [comment]
for completeness, the 2 references to 'WildFly 10.0.0 CR5' should be also changed in: 
https://github.com/openshift/sti-wildfly/blob/ce5335e70728da12181917f1b427b9ba26c38598/10.0/Dockerfile

**Comment by quentinburley** [comment]
also in the README.md the reference to: (10.0.0CR5) should be changed:
https://github.com/openshift/sti-wildfly/blob/b7c05c8ab76522133e08714cc24dccbf0d99436c/README.md

**Comment by bparees** [comment]
thanks, fixing the missed refs here:https://github.com/openshift/sti-wildfly/pull/69
